'''You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
'''

from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        count_s = Counter(s)
        count_t = Counter(t)

        for char in count_t:
            if count_t[char] !=  count_s[char]:
                return char
            
            
# Example usage:
solution = Solution()
print(solution.findTheDifference("abcd", "abcde"))  # Output: "e"
print(solution.findTheDifference("", "y"))          # Output: "y"

# Time Complexity: O(n), where n is the length of string t.
# Space Complexity: O(1), since the size of the character set (lowercase English letters) is constant.

# explaning how Counter works
#*** from an input iterable. Or, initialize the count from another mapping of elements to their counts.nary of characters in the strings.